version: '3.8'

services:
    be:
        container_name: nestjs_api_dev
        build: ./
            # context: ./
            # dockerfile: dev.Dockerfile
        command: npm run start:dev
        env_file:
            - ./env/be.env
        ports:
            - 9001:9001
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules 
        depends_on:
            - mongodb   
    test1_consumer:
        container_name: consumer_1
        build: ./
        command: node dist/message-queue/worker.js
        env_file:
            - ./env/be.env
        depends_on:
            - mongodb
    mongodb:
        image: 'mongo'
        volumes: 
        - data:/data/db
        ports:
            - 27017:27017
        env_file: 
        - ./env/mongo.env

volumes: 
  data: