version: '3.8'

services:
    be:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build: ./
            # context: ./
            # dockerfile: dev.Dockerfile
        command: npm run start:dev
        env_file:
            - ./env/be.env
        ports:
            - 3000:3000
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules 
        depends_on:
            - mongodb   
    mongodb:
        image: 'mongo'
        volumes: 
        - data:/data/db
        ports:
            - 27017:27017
        env_file: 
        - ./env/mongo.env

volumes: 
  data: